/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://d5fswipv2jcbvfhiypkc2uca24.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-qbdyxad6tjcfngoqjyafxusyve",
    "aws_cognito_identity_pool_id": "us-east-2:23a64d45-37ab-4df5-9f5e-9bc46655ee0f",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_l911ybWvm",
    "aws_user_pools_web_client_id": "45drpkt34tg186mk8bqpkkh83m",
    "oauth": {},
    "aws_user_files_s3_bucket": "profile13733-dev",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
